steps:
  # Dockerイメージをビルド
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/lunch-roulette:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/lunch-roulette:latest',
      '.'
    ]

  # Container Registryにプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/lunch-roulette:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/lunch-roulette:latest']

  # Cloud Runにデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'lunch-roulette',
      '--image', 'gcr.io/$PROJECT_ID/lunch-roulette:$COMMIT_SHA',
      '--region', 'asia-northeast1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--set-env-vars', 'SUPABASE_URL=${_SUPABASE_URL},SUPABASE_ANON_KEY=${_SUPABASE_ANON_KEY},DATABASE_URL=${_DATABASE_URL}',
      '--max-instances', '10',
      '--memory', '512Mi',
      '--cpu', '1',
      '--port', '3000'
    ]

# 環境変数を設定（Cloud Build Triggersで設定）
substitutions:
  _SUPABASE_URL: ''
  _SUPABASE_ANON_KEY: ''
  _DATABASE_URL: ''

options:
  logging: CLOUD_LOGGING_ONLY