// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/shops": {
    params: {};
  };
  "/shops/add": {
    params: {};
  };
  "/settings": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/shops" | "/shops/add" | "/settings";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/shops.tsx": {
    id: "routes/shops";
    page: "/shops";
  };
  "routes/shops.add.tsx": {
    id: "routes/shops.add";
    page: "/shops/add";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
};